/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GovernmentRole;

import Business.EcoSystem;
import Business.Enterprises.BankEnterprise;
import Business.Enterprises.Enterprise;
import static Business.Enterprises.Enterprise.EnterpriseType.BankEnterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LoanApprovementWorkRequest;
import Business.WorkQueue.WeatherAnalysisWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shabbir Hussain
 */
public class GovtFundingWorkJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account; 
    Enterprise enterprise;
    EcoSystem system;
    
    /**
     * Creates new form GovtFundingWorkJPanel
     */
    public GovtFundingWorkJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.account=account;
        this.userProcessContainer= userProcessContainer;
        this.enterprise=enterprise;
        this.system=system;
        
    }

    
    
     public void populateFundRequestTable() {
        DefaultTableModel model = (DefaultTableModel) govtWorkRequestJTable.getModel();

        model.setRowCount(0);

        for(Network network: system.getNetworkList() )
        {
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
        {
            for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()){
      
        for (WorkRequest wr : o.getWorkQueue().getWorkRequestList()) {

            
                Object[] row = new Object[5];
                row[0]= wr.getIncome();
                row[1]=wr.getReceiver()==null?null:wr.getReceiver().getUsername();
                row[2]=wr.getStatus();
                String result = ((LoanApprovementWorkRequest)wr).getResult();
                row[3] = result==null?null:result;
                row[4]=wr.getLoanRequired();
                
                model.addRow(row);
            
        }
       }    
            }
        }
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        incomeJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fundingjTextField = new javax.swing.JTextField();
        RequestjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        govtWorkRequestJTable = new javax.swing.JTable();

        jLabel1.setText("Goverment Farmer Funding ");

        jLabel2.setText("Income Of Farmer:");

        incomeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Amount requested for funding :");

        RequestjButton.setText("Request To Bank");
        RequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestjButtonActionPerformed(evt);
            }
        });

        govtWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Income", "Receiver", "Status", "Result", "Loan required"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(govtWorkRequestJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fundingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(RequestjButton)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(incomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(fundingjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(RequestjButton)
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestjButtonActionPerformed
        // TODO add your handling code here:
        LoanApprovementWorkRequest wr = new LoanApprovementWorkRequest();
        wr.setLoanRequired(fundingjTextField.getText());
        wr.setIncome(incomeJTextField.getText());
        wr.setStatus("Sent");
        
        Organization o = null;
        for(Network network: system.getNetworkList() )
        {
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
        {
            if(enterprise instanceof BankEnterprise){
        for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList())
        {
        if(organization instanceof EmployeeOrganization )
        {
            o=organization;
            break;
        }
        
        }
            }
            if(o!= null)
            {
            o.getWorkQueue().getWorkRequestList().add(wr);
            }
        
        }
        
        }
        populateFundRequestTable();
        
        
    }//GEN-LAST:event_RequestjButtonActionPerformed

    private void incomeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestjButton;
    private javax.swing.JTextField fundingjTextField;
    private javax.swing.JTable govtWorkRequestJTable;
    private javax.swing.JTextField incomeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
