/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprises.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ishita
 */
public class BankAdminWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
 private Enterprise enterprise;
 private EcoSystem system;
 private UserAccount account;
    private Organization organization;
    
    
    /**
     * Creates new form BAnkAdminWorkArea
     */
    public BankAdminWorkAreaJPanel(JPanel userProcessContainer,Organization organization, Enterprise enterprise,UserAccount account,EcoSystem system) {
        initComponents();
   this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.enterprise=enterprise;
        this.account=account;
        this.organization=organization;
        }
       
    public void populateTable(){
 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageBankUserJButton = new javax.swing.JButton();
        manageBankEmployeeJButton = new javax.swing.JButton();
        manageBankOrganizationjButton = new javax.swing.JButton();
        bankProcessBtn = new javax.swing.JButton();

        jLabel1.setText("Bank Admin Work Area");

        manageBankUserJButton.setText("Manage User");
        manageBankUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBankUserJButtonActionPerformed(evt);
            }
        });

        manageBankEmployeeJButton.setText("Manage Bank Employee");
        manageBankEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBankEmployeeJButtonActionPerformed(evt);
            }
        });

        manageBankOrganizationjButton.setText("Manage Bank  Organization");
        manageBankOrganizationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBankOrganizationjButtonActionPerformed(evt);
            }
        });

        bankProcessBtn.setText("Bank Process Request ");
        bankProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankProcessBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageBankOrganizationjButton)
                            .addComponent(manageBankEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankProcessBtn)
                            .addComponent(manageBankUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageBankOrganizationjButton)
                .addGap(33, 33, 33)
                .addComponent(manageBankEmployeeJButton)
                .addGap(49, 49, 49)
                .addComponent(manageBankUserJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(bankProcessBtn)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBankUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBankUserJButtonActionPerformed
        // TODO add your handling code here:
        BankUserAccountJPanel muajp = new BankUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("bankUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBankUserJButtonActionPerformed

    private void manageBankEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBankEmployeeJButtonActionPerformed

        ManageBankEmployeeJPanel manageEmployeeJPanel = new ManageBankEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBankEmployeeJButtonActionPerformed

    private void manageBankOrganizationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBankOrganizationjButtonActionPerformed
        // TODO add your handling code here:

        ManageBankOrganizationJPanel manageBankOrganizationJPanel = new ManageBankOrganizationJPanel(userProcessContainer,enterprise,system);
        userProcessContainer.add("manageBankOrganizationJPanel", manageBankOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageBankOrganizationjButtonActionPerformed

    private void bankProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankProcessBtnActionPerformed
        // TODO add your handling code here:
        ProcessRequestBankJPanel prbjp = new ProcessRequestBankJPanel(userProcessContainer,organization,enterprise,account,system);
        userProcessContainer.add("ProcessRequestBankJPanel",prbjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_bankProcessBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankProcessBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageBankEmployeeJButton;
    private javax.swing.JButton manageBankOrganizationjButton;
    private javax.swing.JButton manageBankUserJButton;
    // End of variables declaration//GEN-END:variables
}
