/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprises.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LoanApprovementWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishita
 */
public class ProcessRequestBankJPanel extends javax.swing.JPanel {

        JPanel userProcessContainer;
        private Enterprise eterprise;
        private EcoSystem system;
        private UserAccount account;
        private Organization organization;
        private LoanApprovementWorkRequest loanApprovementWorkRequest;
        private WorkRequest request;        
        private EmployeeOrganization employeeOrganization;
        
    /**
     * Creates new form ManageRequestJPanel
     */
    public ProcessRequestBankJPanel(JPanel userProcessContainer, Organization organization,Enterprise enterprise,UserAccount account,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.eterprise=eterprise;
        this.system=system;
        this.account=account;
        this.employeeOrganization=(EmployeeOrganization)employeeOrganization;
        this.organization=organization;
        
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)govtWorkRequestJTable.getModel();
        dtm.setRowCount(0);
        for(Network network: system.getNetworkList())
        {
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
        {
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            
        for(WorkRequest wr : org.getWorkQueue().getWorkRequestList()){
            
        Object [] row = new Object [5];
        row[0] = wr.getIncome();
        row[1] = wr.getReceiver();
        row[2] = wr.getStatus();
        row[3]= wr.getResult();
        row[4]=wr.getLoanRequired();
        
        dtm.addRow(row);
        
        
        
            
        }
        
        }
        
        
        }
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        govtWorkRequestJTable = new javax.swing.JTable();
        assignjButton = new javax.swing.JButton();
        requestjButton = new javax.swing.JButton();
        processTextField = new javax.swing.JTextField();

        govtWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income", "Receiver", "Status", "Result", "Loan required"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(govtWorkRequestJTable);

        assignjButton.setText("Assign To Me");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });

        requestjButton.setText("Process Request");
        requestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(assignjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(processTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestjButton)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignjButton)
                    .addComponent(requestjButton)
                    .addComponent(processTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = govtWorkRequestJTable.getSelectedRow();
        
                if (selectedRow < 0){
                        return;
                    }
                LoanApprovementWorkRequest wr = (LoanApprovementWorkRequest)govtWorkRequestJTable.getValueAt(selectedRow, 0);
                wr.setStatus("Under Process");
                wr.setReceiver(account);
                
                JOptionPane.showMessageDialog(null, "Successfull");
                
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void requestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = govtWorkRequestJTable.getSelectedRow();
        if(selectedRow < 0)
        {
        return;       
        }
       LoanApprovementWorkRequest wr = (LoanApprovementWorkRequest)govtWorkRequestJTable.getValueAt(selectedRow, 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      govtWorkRequestJTable.getValueAt(selectedRow, 0);
        wr.setStatus("Completed");
        wr.setResult(processTextField.getText());
        JOptionPane.showMessageDialog(null, "Process Successfull");
        
        processTextField.setText("");
        
        
    }//GEN-LAST:event_requestjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton;
    private javax.swing.JTable govtWorkRequestJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField processTextField;
    private javax.swing.JButton requestjButton;
    // End of variables declaration//GEN-END:variables
}
