/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.Enterprises.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Shabbir Hussain
 */
public class FarmerWorkRequestJPanel extends javax.swing.JPanel {
 JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount userAccount;    
    Organization organization;
    
    /**
     * Creates new form FarmerWorkRequestJPanel
     */
    public FarmerWorkRequestJPanel() {
        initComponents();
   this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
           this.userAccount=userAccount; 
this.organization=organization;           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConnecttoBankjButton = new javax.swing.JButton();
        ConnecttoGovtjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ConnecttoBankjButton.setText(" Connect to Bank ");
        ConnecttoBankjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnecttoBankjButtonActionPerformed(evt);
            }
        });

        ConnecttoGovtjButton.setText("Connect to Analyst");
        ConnecttoGovtjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnecttoGovtjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select The Request type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(ConnecttoBankjButton)
                        .addGap(57, 57, 57)
                        .addComponent(ConnecttoGovtjButton)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConnecttoBankjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConnecttoGovtjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConnecttoBankjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnecttoBankjButtonActionPerformed
         
      FarmerBankReqstJPanel fbrJPanel = new FarmerBankReqstJPanel(userProcessContainer, userAccount, (FarmerOrganization) organization,enterprise);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestLabTestJPanel", new FarmerBankReqstJPanel(userProcessContainer, userAccount, (FarmerOrganization)organization,enterprise));
            layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnecttoBankjButtonActionPerformed

    private void ConnecttoGovtjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnecttoGovtjButtonActionPerformed
        
        FarmerGovtrequstJPanel fgrJPanel = new FarmerGovtrequstJPanel(userProcessContainer, userAccount, (FarmerOrganization) organization,enterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new FarmerGovtrequstJPanel(userProcessContainer, userAccount, (FarmerOrganization) organization, enterprise));
        layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_ConnecttoGovtjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnecttoBankjButton;
    private javax.swing.JButton ConnecttoGovtjButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
